dis->right_char = CHAR_MERSEUS;
rsay(dis," Wake up, Faradeus. Today you\nwill be doing my job.");
lsay(dis," *yawns* Really?");
rsay(dis," Yes, really. I need to attend the\ndemon lord meeting today.");
lsay(dis," I'm sure it will go well.");
rsay(dis," I have no doubt about that. But\nI can't leave until I make sure\nthat you can manage things here\nwhile I'm away.");
lsay(dis," I've seen many times how you do\nit. I think I can manage it.");
rsay(dis," Sure, go ahead. Merge the\nsickness hex with the aggression\nhex and give me insanity by\ndragging and dropping it into my\nhand. If you get stuck, let me\nknow by tapping on my hand on");
rsay(dis," the top left corner.");
wait_for(dis, HEX_INSANITY);
lsay(dis," Merseus, I think I... forgot\nsomething.");
rsay(dis," Maybe my amnesia hex stash\ncrept out of containment...\nAnyway, drag and drop two\nhexes on the same tile on your\ncursed paper, and they will\nmerge. Once you merge a hex, it");
rsay(dis," will be added to your knowledge\nlens. You can open the lens on\nthe bottom left and tap on any\nhex to see how it's made. Or you\ncan drag and drop unfinished\nhexes on it - ones with question");
rsay(dis," marks on them, to see what they\nhave inside.");
reveal_hex(dis, HEX_INSANITY);
rloop(dis," Drag and drop to merge. Open\nthe lens on left bottom and tap\non any hex to see how it's made.");
wait_end(dis);
rsay(dis," Great. I think you can manage\ntoday's job. I'll see you later.");
lsay(dis," Bye!");
dis->right_char = CHAR_NULL;
lsay(dis," ...");
lsay(dis," Where are the customers?");
dis->right_char = CHAR_IMPUS;
to_song(dis, SONG_DEEP);
rsay(dis," Ha ha! Bet you didn't see me!");
lsay(dis," You're right, Impus. But why\nwere you hiding?");
rsay(dis," Obviously to jump-scare you.");
lsay(dis," You do know that a son of demon\nlord cannot fear a mere imp?");
rsay(dis," Yeah, keep telling yourself that!\nYour horns are fake, and\nhonestly I'm not even sure\nyou're a demon!");
lsay(dis," I'm just a late bloomer... My real\nhorns will grow soon. At least\nfather told me so. Enough of\nthat, what hex do you want?");
rsay(dis," The reverso! The reverso! Or\nas native Australians call it -\nosrever!");
lsay(dis," They don't call it that.");
wait_for(dis, HEX_REVERSO);
rsay(dis," What's the matter? You don't\nhave reverso?");
lsay(dis," It's hard to find anything in his\npile of hexes. They are all\nunordered and I keep pulling\nuseless ones...");
rsay(dis," Just merge them into one pile!\nCall it the dumpster!");
lsay(dis," I think that is a good idea.");
stop(dis);
rsay(dis," I'm waiting!");
stop(dis);
rsay(dis," I'm waiting!..");
stop(dis);
rsay(dis," I'm waiting!....");
stop(dis);
rsay(dis," I'm waiting!......");
stop(dis);
rsay(dis," Come on!");
stop(dis);
rsay(dis," You can't be serious!");
stop(dis);
rsay(dis," It looks like a recycling symbol.");
stop(dis);
rloop(dis," I'm waiting.");
wait_end(dis);
rsay(dis," Thanks!!!");
lsay(dis," No problem. By the way, why do\nyou need reverso?");
rsay(dis," I'm participating in a race with\nno rules, and my strategy is to\nuse reverso hex on my\nopponents to make them run\nbackwards!");
lsay(dis," Very creative. But be careful,\nreverso effects are not as\nsimple as you think.");
rsay(dis," Don't worry, I still have good\nold banana trap ready!");
lsay(dis," Good luck then.");
dis->right_char = CHAR_NULL;
lsay(dis," I hope other customers will ask\nfor something simple too.");
dis->right_char = CHAR_VAMPIRUS;
rsay(dis," I'll get a... do you have anything\nwith blood?");
lsay(dis," I'm not sure... We sell hexes -\nnot blood.");
rsay(dis," Then - can I get something that\ngives blood?");
lsay(dis," Ok.");
wait_for(dis, HEX_VIOLENCE);
rsay(dis," Does my nose deceive me, or do\nyou have human blood in you?");
lsay(dis," I didn't drink any today, so no.");
rsay(dis," That is weird... You smell like you\nalways carry a fresh pack with\nyou!");
stop(dis);
rsay(dis," You don't have anything with\nblood?");
lsay(dis," I think I do but I can't find it.");
rsay(dis," Maybe try going for hexes that\nhave red in them.");
stop(dis);
rsay(dis," Have you tried the violence\nhex? Check your lens, maybe it\nhas something!");
reveal_hex(dis, HEX_VIOLENCE);
rsay(dis," Have you tried the violence\nhex? Check your lens, maybe it\nhas something!");
rloop(dis," Check your lens, maybe it has\nsomething!");
wait_end(dis);
rsay(dis," Thank you! Something good in\nhell does exist!");
lsay(dis," Why did you go here if you don't\nlike it here?");
rsay(dis," My cousin died, so I went to visit\nhim. Somehow he ended up in\nheaven though, so I'm a bit stuck\nhere, as there is no hiding from\nhell's sun, unlike mortal world\nsun fragments.");
lsay(dis," I thought our sun doesn't\naffect vampires. If it helps, you\ncan spend the day here.");
rsay(dis," Thank you! No one was as\nwelcoming as you are! And I\nthought all demons are rude. But\nyou're a good demon!");
dis->right_char = CHAR_NULL;
lsay(dis," Good demon... Merseus always\ntells me I need to be like others...\nBut I just can't.");
dis->right_char = CHAR_SHADOWUS;
lsay(dis," Shadowus, long time no see!");
rsay(dis," Shh... be quiet...");
lsay(dis," What? why?");
rsay(dis," I shouldn't be there. Don't tell\nMerseus I was there.");
lsay(dis," Wait, are you going to rob my\nfather again?");
rsay(dis," I'm not a thief.");
lsay(dis," Come on, last time you visited,\nour gold chamber was emptied.");
rsay(dis," Nuh-uh.");
lsay(dis," What do you mean nuh-uh?");
rsay(dis," Alright, alright, I'll just buy a\nhex and be off. Give me amnesia\nhex.");
wait_for(dis, HEX_AMNESIA);
rsay(dis," Take your time.");
stop(dis);
rsay(dis," I can tell you how its made for 10\nFierce.");
lsay(dis," I sell it for 10 Fierce...");
reveal_hex(dis, HEX_AMNESIA);
rloop(dis," I think you can find some\ninformation in your lens.");
wait_end(dis);
lsay(dis," here is your amnesia hex.");
rsay(dis," Thank you.");
to_song(dis, SONG_FOREST);
dis->right_char = CHAR_NULL;
lsay(dis," Wait, who was I talking to just\nnow?");
dis->right_char = CHAR_SHADOWUS;
rsay(dis," Hello, Faradeus!");
lsay(dis," Who are you?");
rsay(dis," Your father's friend, he needed\nto get some gold from the\nchamber, mind helping me open it?");
lsay(dis," Sure thing! Just use the secret\ncode *tells the secret code*");
dis->right_char = CHAR_NULL;
lsay(dis," What a nice guy. Strange father\nnever mentioned him.");
dis->right_char = CHAR_CERBERUS_JR;
to_song(dis, SONG_SHRINE);
rsay(dis," WOOF!");
lsay(dis," Lil Cerberus! How's your old dog\ndoing?");
rsay(dis," WOOF!");
lsay(dis," Got it. Sleep deprived as\nalways... I might have some hex to\nhelp the cause, this one will be on\nthe house!");
rsay(dis," WOOF!");
wait_for(dis, HEX_PROCRASTINATION);
rsay(dis," WOOF!!");
lsay(dis," Hades is so cruel!");
stop(dis);
rsay(dis," WOOF!!!");
lsay(dis," No, I didn't watch it.");
reveal_hex(dis, HEX_PROCRASTINATION);
rloop(dis," WOOF!");
wait_end(dis);
rsay(dis," Woof.");
lsay(dis," Hope it helps.");
dis->right_char = CHAR_NULL;
lsay(dis," Things are going well. Although\nmerging new hexes is getting\nharder and harder...");
dis->right_char = CHAR_ANGELUS;
rsay(dis," Be not afraid.");
lsay(dis," How did you get there?");
rsay(dis," We come to your soul. To save\nyou.");
lsay(dis," I'm good.");
rsay(dis," You don't know what awaits you...");
lsay(dis," Buy a hex or I'm kicking you out.");
rsay(dis," War hex please.");
wait_for(dis, HEX_WAR);
lsay(dis," I'm confused, you're here for\nme?");
rsay(dis," Affirmative. Your soul is lost\nhere.");
lsay(dis," There must be a mistake, demon\nsouls don't get lost.");
rsay(dis," Your soul is neigh of demon.");
stop(dis);
rsay(dis," Human, do you wish to escape\nhell?");
lsay(dis," Thats insulting, I'm not a human!");
rsay(dis," So lost...");
lsay(dis," For an angelic automaton you're\nvery expressive.");
stop(dis);
rsay(dis," The lens is calling you. It is your\ndestiny to give us war.");
reveal_hex(dis, HEX_WAR);
rloop(dis," The lens is calling you.");
wait_end(dis);
rsay(dis," Your demon father only seeks\nbenefit from you.");
lsay(dis," I know. we made a deal, at age 21\nI hand over my body.");
rsay(dis," That is horrific.");
lsay(dis," It's fine, he gives me his body.\nOld, but powerful! I would do it\ntoday, but ritual requires me to\ndrink, so I need to be legal\ndrinking age.");
rsay(dis," If you ever wish to change fate,\ncome to mortal realm.");
lsay(dis," Yeah, yeah, go before someone\npowerful finds you.");
dis->right_char = CHAR_NULL;
lsay(dis," Never thought I would meet a\nbeing from heavens here.");
dis->right_char = CHAR_PIDGEONUS;
rsay(dis," Good morning, sir. I would like to\nget a plague hex.");
lsay(dis," One plague hex coming right up.");
wait_for(dis, HEX_PLAGUE);
lsay(dis," Are you an actual pigeon?");
rsay(dis," Why of course! In fact, I'm a\npigeon prince.");
lsay(dis," Why would you need a plague\nhex then?");
rsay(dis," Simple - my kingdom wages war on\nrat kingdom. We are,\nunfortunately, losing. So to turn\nthe tides our greatest minds\ncame up with a brilliant idea -\nplague the rats.");
lsay(dis," The lore is so deep...");
stop(dis);
lsay(dis," Aren't you afraid the plague will\nspread to your people?");
rsay(dis," It may happen. But it is a risk we\nhave to take. Otherwise rats will\nconquer us.");
stop(dis);
rsay(dis," Please do hurry. I reckon your\nlens revealed the secret of\nplague.");
reveal_hex(dis, HEX_PLAGUE);
rloop(dis," I reckon your lens revealed the\nsecret of plague.");
wait_end(dis);
rsay(dis," Me and my pigeons are in debt\nfor your service!");
lsay(dis," Don't worry. I don't take extra\nfees.");
dis->right_char = CHAR_NULL;
lsay(dis," Why do I feel like it was\nsupposed to be a moral dilema?");
dis->right_char = CHAR_BLOODLETTUS;
lsay(dis," Welcome, Bloodlettus.");
rsay(dis," Faradeus? Do you run the shop\nnow?");
lsay(dis," Only for today. Merseus is at\nthe demon lord meeting.");
rsay(dis," I see. I will get a famine hex then.");
wait_for(dis, HEX_FAMINE);
lsay(dis," How are you going to use it?");
rsay(dis," Make villages starve, so they\nhave to use my services.");
lsay(dis," Is it legal?");
rsay(dis," We're in hell, who cares?");
lsay(dis," Merseus does...");
rsay(dis," He is a demon lord, they have\ndifferent standards.");
stop(dis);
lsay(dis," How do you always have blood on\nyou?");
rsay(dis," I stretch my roots deep into the\nground and harvest small\ncreatures that live\nunderground.");
stop(dis);
rsay(dis," Some say famine comes from\npeople being weak and lazy, but\nthe reality is - it comes when\npeople silence bright minds that\ntry to save the day.");
reveal_hex(dis, HEX_FAMINE);
rloop(dis," Did you check your lens?");
wait_end(dis);
lsay(dis," Here is your famine hex. Also, do\nyou want to meet someone who is\nas exited about blood as you\nare?");
rsay(dis," I would like to meet such a\nperson.");
lsay(dis," I have new vampire friend in\nguest room. His name is Vampirus.");
rsay(dis," Great! I always favored\nvampires in vampire vs werewolf\ndebates.");
dis->right_char = CHAR_NULL;
lsay(dis," That's it for today. I think I'm\nfinished.");
dis->right_char = CHAR_MERSEUS;
rsay(dis," Not so fast, young man.");
lsay(dis," Merseus? You're back! Just in\ntime for closing.");
rsay(dis," Yes. But I'm here to order the\nfinal hex.");
lsay(dis," Why... You can make them\nyourself.");
rsay(dis," This one - no. There is a secret\nthat I cannot unravel by birth.\nBut you are different.");
lsay(dis," What is it?");
rsay(dis," Lets make the hex first. this one\nis -");
to_song(dis, SONG_HIMA);
rsay(dis," death.");
wait_for(dis, HEX_DEATH);
lsay(dis," Can you tell me why you can't\nmake it? You're so powerful it\nshould be easy!");
rsay(dis," My power is what makes it\nimpossible.");
stop(dis);
lsay(dis," Stop hiding the truth! Just say\nyou want to test me.");
rsay(dis," That would be a lie.");
stop(dis);
lsay(dis," Death hex is just absence of all\n5 senses! It's not that difficult.");
rsay(dis," Death is more than that...");
reveal_hex(dis, HEX_DEATH);
rloop(dis," Lense will guide you.");
wait_end(dis);
rsay(dis," I spend hundred years trying to\nfathom it. War was the easiest -\nit is what we do. Famine was not\nthat far away - that is what we\ninflict. Plague was not easy, but\nafter many tries I understood it.");
rsay(dis," But death - it always escaped\nme. Yet, you made it.");
lsay(dis," Yes. But why? You're way\nsmarter than me.");
rsay(dis," It's not the mind. But the soul.");
rsay(dis," Faradeus. You're not my son.");
lsay(dis," What? But... That's not possible.");
rsay(dis," I stole you from kind people in\nthe mortal realm. As I wanted to\nlearn the truth behind death -\nand mortals are the only answer.\nIt wasn't easy raising you as\nmortals are fragile. But");
rsay(dis," definitely worth it.");
lsay(dis," So all the weird things about me\nare just because I'm not a\ndemon?");
rsay(dis," Yes. You should be in the mortal\nrealm. Living a normal human life.");
lsay(dis," How about our deal?");
rsay(dis," It still holds. It was my plan from\nthe beginning to take over your\nbody. But truth is - you won't be\nable to take over mine.");
lsay(dis," So Angelus was right. You\ntricked me.");
rsay(dis," I am a demon. And the contract\nspecifies that you must be able\nto claim my body to take over it.\nThere will be no mercy from my\nside.");
lsay(dis," Can I at least spend rest of my\nlife someplace else?");
rsay(dis," Sure. But you won't be able to\nrun from me.");
lsay(dis," I know. See you in 2 years. I will\nbe in the mortal realm.");
roll_credits(dis);
